### ISSUE TITLE
Calamares Initialization Failed

### ISSUE THREAD

**Issue by aamirali51** [arch-linux-calamares-installer/alci-iso#2]
Dear Sir,
Calamares giving me error after trying to install the iso build using ALCI-DEV 

The error is:  ALCI cannot be installed. Calamares unable to load all of the configured modules 

users@users
users@users

**Comment by arcolinuxz** [comment]
rebuild Calamares already online in articles and videos

search first

**Comment by Mistreaper** [comment]
After rebuilding calamares the error still persists.

**Comment by arcolinuxz** [comment]
you need to be sure the new calamares is on the iso

**Comment by arcolinuxz** [comment]
if you do not change anything to our scripts
then there should be zero differences if I build or if you build it
if we are on the same distribution and if we are both up to date

**Comment by arcolinuxz** [comment]
booting up and rebuilding it myself

**Comment by arcolinuxz** [comment]
Steps to take
rebuild Calamares - up one number
put it on the repo - push it 
wait for it to be visible 
rebuild the iso - check it is the new version that comes in (github can be slow)
you need to add a repo or something to be sure YOUR calamares is on the iso
it is working here now
and I just installed it

it is literally here
https://alci.online/rebuild-calamares-when-one-of-its-dependencies-gets-an-update-boost-and-boost-libs/

**Comment by Mistreaper** [comment]
Yes, the issue is resolved, thank you.

**Comment by arcolinuxz** [comment]
great

**Comment by aamirali51** [comment]
Dear Eric,

First of All thank you very much for these efforts... You are doing a amazing job to educate everyone and we thank you for that.. issue has been resolved...
