### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by LeVraiArdox** [arch-linux-calamares-installer/alci-iso#4]
Hello. I added ALCI to my distro, but an error appears: "/bin/sh: /usr/bin/alci-displaymanager-check: permission denied". I checked the ownership of the file, the permissions of the live user and even if it is executable. How can i repair this ?

**Comment by arcolinuxz** [comment]
it needs to be executable that is one.
but it is a script we run from within Calamares
that means it is sudo !!
even though in the script there is no sudo mentioned

**Comment by LeVraiArdox** [comment]
But i don't understand how to fix this. Isn't calamares executed as sudo ?

**Comment by arcolinuxz** [comment]
our calamares is executed as root
back to the basics
compare what you have
compare what we have
