### ISSUE TITLE
boot erro: "/dev/disk/by-label/" device did not show upp after 30 seconds"

### ISSUE THREAD

**Issue by AtharLinux** [arch-linux-calamares-installer/alci-iso#7]
Hello, upon calamares/archiso install on an external storage device (target)
I get this error:
Mounting '/dev/disk/by-label/' to '/run/archiso/bootmnt'
ERROR: "/dev/disk/by-label/" device did not show up after 30 seconds"
![image](https://github.com/arch-linux-calamares-installer/alci-iso/assets/156441713/e21655e4-ca08-4338-8537-001599417e82)

**Comment by arcolinuxz** [comment]
tell me what version you are using
