### ISSUE TITLE
/etc/motd is not clean after installation

### ISSUE THREAD

**Issue by nxuv** [arch-linux-calamares-installer/alci-iso#8]
![Screenshot_2024-01-24-03-17-59-738_com termux-edit](https://github.com/arch-linux-calamares-installer/alci-iso/assets/60989682/266340f3-cbfe-4bba-a392-aaf050555307)

Whenever I open tty or ssh into machine it shows me that message

**Comment by nxuv** [comment]
Ok, so, for some reason `/etc/motd` didn't get cleared on installation

**Comment by arcolinuxz** [comment]
fun right

remove it

**Comment by arcolinuxz** [comment]
Here is an example 

https://github.com/arch-linux-calamares-installer/alci-iso-pure/blob/master/archiso/airootfs/etc/motd

just do not put it in there

**Comment by nxuv** [comment]
Yea, that thing, I cleaned it on my machine, but why it was staying filled

Also why would I need packages like `archinstaller` after already having it installed

**Comment by arcolinuxz** [comment]
remove anything you do not want
I think you mean the archinstall application
remove it

**Comment by arcolinuxz** [comment]
change alci anyway you want
it is just a tutorial - a template - something to get you started - a way to learn how to create your own iso/distro
it is not written in stone - change it

**Comment by nxuv** [comment]
Sure... Ok then
