### ISSUE TITLE
Issue building with chaotic-aur

### ISSUE THREAD

**Issue by AlexanderWKoenig** [arch-linux-calamares-installer/alci-iso#9]
Hello,

I really like this project and it worked well for my older builds (maybe a year ago)
Now I tried to build the iso again after pulling and rebasing my stuff, but it fails with PGP signature error.

```
(1317/1317) checking keys in keyring                          [##################################] 100%
(1317/1317) checking package integrity                        [##################################] 100%
error: chaotic-mirrorlist: signature from "Erik Dubois <erik.dubois@gmail.com>" is unknown trust
:: File /mnt/home/pacman-cache/pkg/chaotic-mirrorlist-20240306-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: chaotic-keyring: signature from "Erik Dubois <erik.dubois@gmail.com>" is unknown trust
:: File /mnt/home/pacman-cache/pkg/chaotic-keyring-20230616-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
Moving pkglist.x86_64.txt
########################
```

On my main system I can reinstall chaotic-keyring and chaotic-mirrorlist with `sudo pacman -S chaotic-keyring chaotic-mirrorlist` without errors. Has something changed regarding chaotic-aur packages in alci-iso?

I've also tried building without chaotic-keyring and chaotic-mirrorlist in packages.x86_64 but the build failed later down the road. Since I use packages from chaotic-aur in packages.x86_64

**Comment by arcolinuxz** [comment]
Type sudo pacman -Scc
cleaning the cache and get the packages back in

**Comment by arcolinuxz** [comment]
The way I read it - it is not Chaotic but ArcoLinux keys that should be fixed.

We type "fixkey" in a terminal on ArcoLinux

**Comment by arcolinuxz** [comment]
I just build two ISOs - Alci-iso and Alci-iso-dev
I guess we should compare notes

**Comment by AlexanderWKoenig** [comment]
Thanks. `sudo pacman -Scc` did work. So it seems like I had some outdated packages in paman cache.
